//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchEverything.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchEverything.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FileNameText {
            get {
                return ResourceManager.GetString("FileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string FileSizeText {
            get {
                return ResourceManager.GetString("FileSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filesearch.
        /// </summary>
        internal static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to {0} failed!.
        /// </summary>
        internal static string infoConnectionToServerFailed_arg1 {
            get {
                return ResourceManager.GetString("infoConnectionToServerFailed_arg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching file information....
        /// </summary>
        internal static string infoFetchingFileDetails {
            get {
                return ResourceManager.GetString("infoFetchingFileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string LastModifiedText {
            get {
                return ResourceManager.GetString("LastModifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string lblSearchText {
            get {
                return ResourceManager.GetString("lblSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string menuItemClose {
            get {
                return ResourceManager.GetString("menuItemClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string menuItemFile {
            get {
                return ResourceManager.GetString("menuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match &amp;case.
        /// </summary>
        internal static string menuItemMatchCase {
            get {
                return ResourceManager.GetString("menuItemMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match &amp;path.
        /// </summary>
        internal static string menuItemMatchPath {
            get {
                return ResourceManager.GetString("menuItemMatchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match &amp;whole word.
        /// </summary>
        internal static string menuItemMatchWholeWord {
            get {
                return ResourceManager.GetString("menuItemMatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max &amp;results per server:.
        /// </summary>
        internal static string menuItemMaxHitsPerServer {
            get {
                return ResourceManager.GetString("menuItemMaxHitsPerServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string menuItemOptions {
            get {
                return ResourceManager.GetString("menuItemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;icons.
        /// </summary>
        internal static string menuItemShowRealIcons {
            get {
                return ResourceManager.GetString("menuItemShowRealIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string PathNameText {
            get {
                return ResourceManager.GetString("PathNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string RowVisibleText {
            get {
                return ResourceManager.GetString("RowVisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serverpath.
        /// </summary>
        internal static string ServerPathText {
            get {
                return ResourceManager.GetString("ServerPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerURI.
        /// </summary>
        internal static string ServerURIText {
            get {
                return ResourceManager.GetString("ServerURIText", resourceCulture);
            }
        }
    }
}
