//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchEverything.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string># each line contains a mapping between a local ETP server filepath and the filepath the user sees.</string>
  <string># Format is: &lt;ETPUri&gt;;&lt;serverpath&gt;;&lt;userpath&gt;</string>
  <string># matching is done ""first found"", so the order matters</string>
  <string># username and password can be ommited from the URIs</string>
  <string />
  <string>etp://vsvr1:21/;F:\Usr\Pilz\;G:\</string>
  <string>etp://vsvr1:21/;F:\Usr\Software\;I:\</string>
  <string>etp://vsvr1:21/;F:\Usr\UserHome\;J:\</string>
  <string>etp://vsvr1:21/;F:\Usr\NCHomag\;H:\</string>
  <string>#etp://vsvr1:21/;F:\UsrSys\Buchhaltungsbackup\;R:\</string>
  <string>#etp://vsvr1:21021/;F:\Administration\;\\vsvr1\Administration\</string>
  <string />
  <string>#etp://vsvr1:21021/;F:\UsrSys\Buchhaltungsbackup\;R:\</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PathMappings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PathMappings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideNonMappedFolders {
            get {
                return ((bool)(this["HideNonMappedFolders"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideInaccessible {
            get {
                return ((bool)(this["HideInaccessible"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string># each line starting with etp:// is interpreted as a connection-URI </string>
  <string># for a SearchEverything ETP server</string>
  <string># Uri is in the form etp://[(&lt;username&gt;|&lt;username&gt;:&lt;password&gt;)@]&lt;hostname_or_ip&gt;[:&lt;port&gt;]/</string>
  <string># this Uri must also be used in the PathMappings</string>
  <string />
  <string>etp://etp@vsvr1:21/</string>
  <string>#etp://etp:etp@vsvr1:21021/</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServerList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServerList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatchWholeWord {
            get {
                return ((bool)(this["MatchWholeWord"]));
            }
            set {
                this["MatchWholeWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatchRegex {
            get {
                return ((bool)(this["MatchRegex"]));
            }
            set {
                this["MatchRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatchCase {
            get {
                return ((bool)(this["MatchCase"]));
            }
            set {
                this["MatchCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatchPath {
            get {
                return ((bool)(this["MatchPath"]));
            }
            set {
                this["MatchPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string MaxResultsPerServer {
            get {
                return ((string)(this["MaxResultsPerServer"]));
            }
            set {
                this["MaxResultsPerServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRealIcons {
            get {
                return ((bool)(this["ShowRealIcons"]));
            }
            set {
                this["ShowRealIcons"] = value;
            }
        }
    }
}
